### ISSUE TITLE
tutorial part 9 view form.cleaned_data

### ISSUE THREAD

**Issue by EliseRemise** [mdn/django-locallibrary-tutorial#20]
I am new to Python and Django so I might be missing something. However in part 9 of the tutorial when creating the view renew_book_librarian function there is this line:

book_instance.due_back = form.cleaned_data['renewal_date'] 

in the if book_renewal_form.is_valid() evaluation code block. should that not be:

book_instance.due_back = book_renewal_form.cleaned_data['renewal_date']

**Comment by hamishwillee** [comment]
I think you are saying [that this line](https://github.com/mdn/django-locallibrary-tutorial/blob/3b981a0ae5c546ba7e73e5171bf7c878e7df2c50/catalog/views.py#L115) should be `book_renewal_form.cleaned_data['renewal_date']` rather than `form.cleaned_data['renewal_date']`

If so, no. The object we are cleaning is named `form`. We create it above using `form = RenewBookForm(request.POST)`.

**Comment by EliseRemise** [comment]
Thanks, is see now where I went wrong. The example code on [https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms] uses book_renewal_form as variable name and here on github its called form.  Got the two sources mixed up.

**Comment by hamishwillee** [comment]
No worries! I'll leave this open as at some point should try see if the docs and github can be aligned.
