### ISSUE TITLE
tutorial part 3

### ISSUE THREAD

**Issue by tinyfiddle4864** [mdn/django-locallibrary-tutorial#64]
in models.py

 class Book(models.Model):
    title = models.CharField(max_length=200)

    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null = True)

    summary = models.TextField(max_length = 1000, help_text= 'Enter a brief description of the book')

    isbn = models.CharField(
        'ISBN', max_length=13, help_text='13 character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    genre = models.ManyToManyField(Genre, help_text = 'Select a genre for this book')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-details', args=[str(self.id)])

there is no self.id in class Book and is giving an error
the get_absolute url seems to not work as the foriegn keys are not getting linked somehow

**Comment by hamishwillee** [comment]
Is this failing on this repo or your own version? 
I assure you that Book does have self.id - every model has one auto created by default.

**Comment by tinyfiddle4864** [comment]
i copy pasted the code and tried as well, but still it was failing for me.

**Comment by hamishwillee** [comment]
No, I mean if you try this particular repo code in all its glory, does it work?

**Comment by tinyfiddle4864** [comment]
no, still it shows the same error.

**Comment by hamishwillee** [comment]
OK, so this all works and builds fine with the right environment, so probably you have just imported the current requirements/versions as you have gone through the tutorial. One of these has been updated since the tutorial was written, breaking the code.

You can test this by creating a clean environment, then import the requirements.txt/follow the steps as shown in https://github.com/mdn/django-locallibrary-tutorial#quick-start

If that works then you've done nothing wrong in your code and the example will need and update. If it does not work then i'm a bit stumped.

**Comment by tinyfiddle4864** [comment]
Yes it seems to work now with the quick setup but when i opened vscode it still shows errors, i don’t understand whats wrong

**Comment by hamishwillee** [comment]
The fact it works tells us that one of the dependencies has changed since the tutorial was created, and now that part of the code (and the dependencies) should be updated. To find out which, you look at https://github.com/mdn/django-locallibrary-tutorial/blob/master/requirements.txt
Then in your old environment you compare to see what has changed. For example, what version of Django are you using?

Also note that VSCode reporting errors is not something I can help with - I coded this in a text editor.

**Comment by tinyfiddle4864** [comment]
the only difference in my old environment was that django version was 2.2 as 2.1 has been deprecated.
Thank you so much for the help!
