### ISSUE TITLE
Discrepancy in test_views RE permission error tests

### ISSUE THREAD

**Issue by isherifwilson** [mdn/django-locallibrary-tutorial#66]
While working through [part 10](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Testing), I ran into some behavior that has confused me.

1. It seems that the status code indicated in the tutorial is incorrect in one of our unit tests (`RenewBookInstancesViewTest.test_redirect_if_logged_in_but_not_correct_permission()`), based on the behavior I've seen + what is shown in the file in the repository ([link to relevant line, 330](https://github.com/mdn/django-locallibrary-tutorial/blob/acf2a446cdb45edd9105303b15dd86fca4458c85/catalog/tests/test_views.py#L330)). The test failed before I updated the status code to 302, and its behavior makes sense as such (when logged in with a user without the relevant permission, it redirects to a login page with a prompt at the top to provide credentials for a user that has permission).
2. It seems that the error code again is wrong in `AuthorCreateViewTest`, as the `test_redirect_if_logged_in_but_not_correct_permission()` unit tests fails, returning:
 ```
self.assertEqual(response.status_code, 403)
AssertionError: 302 != 403
```
This is quite confusing as, when replicating the test in a browser results in a "403 Forbidden" and `"GET /catalog/author/create/ HTTP/1.1" 403 22` is shown in the terminal.

As far as I can see, the primary difference is that `renew_book_librarian()` function uses the `@permission_required` decorator rather than the `PermissionRequiredMixin` used in the `AuthorCreate`

**Comment by hamishwillee** [comment]
@isherifwilson Thanks very much - good catch. Yes it is inconsistent. 

Arguably the behaviour in RenewBookInstancesViewTest is wrong - if you're not logged and you're trying to do something that requires permissions then you should be taken to a login screen to log in - ie the status code will be 302 (redirect). If you are logged in but have the incorrect permissions then you should get 403 forbidden. Redirecting to login again when you're already logged in is annoying

As you say, the default permissions on function and class based views are different (this may have changed since I designed the test). Essentially though we need two decorators in the function view case, and the permission one has to raise an exception:
```
@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):	def renew_book_librarian(request, pk):
```

I have fixed up the code in #76 and the docs. The test for this case is now: `test_forbidden_if_logged_in_but_not_correct_permission`
