### ISSUE TITLE
remove uses of fields = '__all__'

### ISSUE THREAD

**Issue by morenoh149** [mdn/django-locallibrary-tutorial#68]
there are many uses of `fields = '__all__'` this is an antipattern. If in the future the model is given a field that should not be updatable it will be exposed.

Better to explicitly list the fields than be implicit.

**Comment by hamishwillee** [comment]
I'm currently updating the Express docs, and will then move back to Django. I'll look at this then. Generally I'll be following whatever the patterns are recommended by the latest version of the Django docs. Even if that were to be "less correct", it is less disruptive for learners than having different paradigms than what they see in the "canonical docs source".

**Comment by morenoh149** [comment]
agreed. I don't think the django tutorial uses __all__ .

**Comment by hamishwillee** [comment]
Basic investigation on this.  [Django's position](https://docs.djangoproject.com/en/3.1/topics/forms/modelforms/#selecting-the-fields-to-use) is that using `__all__` or excluding is fine provided you have reason not to be concerned about the security risks (e.g. fields being in the form that should not be; in particular in future if new fields are added when you are not thinking about it). This does not come up in the normal Django tutorial. 

The uses in the MDN Django docs [are intentional](https://wiki.developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms#Views) - ie to demonstrate the fact that it exists. The uses in this project follow that.

My take on this is that the Author _code_ at above link should stay the same, for the same reason - ie just one instance of using `__all__` in the docs and this project. However we need a much more clear statement in the docs about the risk of using __all__. Also we should update [BookCreate and BookUpdate](https://github.com/mdn/django-locallibrary-tutorial/blob/master/catalog/views.py#L154) to list the fields.

**Comment by hamishwillee** [comment]
Fixed up the docs and code to explain not to use `__all__ without care: https://wiki.developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms#ModelForms

Code updates to match this in #75
