### ISSUE TITLE
Adding more challenges, explanations to challenge solutions

### ISSUE THREAD

**Issue by iojeda** [mdn/django-locallibrary-tutorial#74]
Hi 

Thanks for creating this excellent tutorial for Django beginners.

It is the best I've found so far, even better than the one provided by Django official site.

While following the tutorial I really enjoyed having some challenges at the end of each step, that's something that you guys can expand on maybe? (adding more challenges)

Also another thing that will be very beneficial for new programmers is understanding some architecture decisions when developing ([Models Challenge](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Models#Language_model_—_challenge)) 

So I think it will be good to have in the next chapter of working with models an explanation on why Language was implemented that way and not in any other possible way. 

That can be applicable to any challenge that requires architecture decisions in other chapters.

(_Sorry if this is not the appropriate place to comment about this, I didn't found any other place where to post this_)

**Comment by hamishwillee** [comment]
@iojeda Thanks for your feedback. 

Setting challenges is more challenging than you might think! Essentially you have to think of some task that tests a part of the knowledge that the user just developed from reading (in a meaningful way), and then you have to develop your own solution to that task, and provide useful documentation. They can't be too hard, and they can't be trivial - or people feel patronised.

I think that we've picked just about the right level here. I'm not saying that more challenges wouldn't be fun, but that the effort to do so would not add sufficient value to justify it. If I wanted to put more effort into this I'd extend the example another chapter covering some other aspect of web development!

> Also another thing that will be very beneficial for new programmers is understanding some architecture decisions when developing (Models Challenge)

What we do in these sections is point to the code. Now I could spell out the reasons, but I was hoping that people would look at the solution and _think_ about why we did it that way. That makes sense because the pages associated with these challenges all explain the logic for making these _kinds_ of decision. Also because they aren't really to do with Django or code - they are to do with the real system that you are working with. I'm just trying to hint at things, not do a course in design!

I will take this on board, but I do not plan on acting on it for now. Hence will close this issue.

But just for your information about those decisions for the Language case:

> Should "language" be associated with a Book, BookInstance, or some other object?

I made language part of the Book because to my mind a book in French and a book in English are _different_ - so every book has its own language, and all imprints of a book are in that particular language. A real library might well consider that all books are the same irrespective of language and that it is the imprint that decides what language a book has. These are questions you'd resolve with the actual library during your design process :-)

> Should the different languages be represented using model, a free text field, or a hard-coded selection list?

I decided not to use free text because if you do that then it is easy for someone to make a spelling mistake and end up mis-filing books. Much better for a user if it gets entered once and they never have to enter it again. I could have hard coded a selection list, but then I'd be forcing librarian to have all languages, even if they only support a few, and also make work for me to update if a new language variant comes along. 

So that implies I need the value to be dynamically updated - ie a database field. I use a ForeignKey because each book only has one language so it is a 1:1 relationship.

I'm glad you enjoyed this!

**Comment by hamishwillee** [comment]
PS If you see a _specific_ good challenge and challenge solution, you are welcome to propose it and implement it :-). Provided it is clear benefit to other users we'll support you with advice etc.

**Comment by iojeda** [comment]
Hi @hamishwillee,
Thanks for the detailed explanations and for your work on this project.

I would love to contribute but unfortunately I don't feel confident enough yet to do so since I am just starting with Django.

I will be more than happy to collaborate once I get a deeper and broader knowledge on the subject.

I can think of one challenge that can be interesting maybe....
**Challenge**: 

- Introducing support to allow for multiple Authors in a book.

After allowing people to try and figure that out maybe provide a solution that contains steps followed for resolution.

- work on updated models and views to represent books with multiple Authors
- Implications on updating the model ( from 1 to many relationship to many to many)
- Will Django migrations do the job alone or it will require additional database work on the side to adapt current data?
- etc..

**Comment by hamishwillee** [comment]
@iojeda Well, you've already helped by adding #77, so I you've already shown you can make useful contributions :-)

We show users how to do 1:1 and 1>many in the docs, but we only challenge on the 1:1 case (for language). So I agree this would be a reasonable challenge. While I'm tempted to try it (if only because I don't know if updating the migrations would be enough!). But the work for developing this does not show "enough" extra to justify **for me**. Even creating those UML diagrams eats up a lot of time!

If you wanted to do this I would support you though.
